# Generated by Django 4.0.5 on 2022-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=100)),
                ('product_id', models.PositiveIntegerField()),
                ('product_selling_price', models.FloatField()),
                ('qty', models.PositiveIntegerField()),
                ('total_amount', models.FloatField(null=True)),
                ('total_cost', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='order_image')),
                ('coupon', models.PositiveIntegerField(blank=True, null=True)),
                ('payment', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'success'), ('shipped', 'shipped'), ('out of selivery', 'out of delivery'), ('deliverd', 'deliverd'), ('cancelled', 'cancelled')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
