# Generated by Django 4.0.5 on 2022-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mac', 'mac'), ('ipad', 'ipad'), ('iphone', 'iphone'), ('watch', 'watch'), ('airpods', 'airpods'), ('homepod', 'homepod')], max_length=100)),
                ('image', models.ImageField(upload_to='category_images')),
                ('status', models.BooleanField(default=True, help_text='0-hidden, 1-default')),
                ('trending', models.BooleanField(default=False, help_text='0-default, 1-trending')),
                ('offfer', models.BooleanField(default=False, help_text='0-default, 1-offer')),
                ('order_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
